services:
  chatten:
    build: .
    container_name: chatten
    restart: unless-stopped

    environment:
      TZ: Europe/Stockholm

    mem_limit: 2g
    cpus: 2.0
    pids_limit: 200

    volumes:
      - ./data:/data
      - ./static:/app/static
      - ./templates:/app/templates

    ports:
      - "8000:8000"